version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    lll:
      line-length: 120
  exclusions:
    generated: lax
    rules:
      - path: (.+)_test.go
        linters:
          - lll
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
