---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@664bb9ea2b65348e4c3aef4f94ab73f9f0b15b3e # v44.0.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
